blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/messages/compose?recipient_id=1253390266943385604
    about: Cualquier duda o consulta puedes mandarnos un DM por Twitter
